spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server.Pet-Clinic.local
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server.Pet-Clinic.local/eureka/
